
CREATE DATABASE db;

USE db;

CREATE TABLE EMPLOYEES(
	ID INT(8) NOT NULL AUTO_INCREMENT=1 PRIMARY KEY,
	NAME VARCHAR(150) NOT NULL,
	START_DATE DATE NOT NULL,
	DEPARTMENT ENUM('ADMIN', 'DEV', 'SALE') NOT NULL,
	/* 1: RESP, 2: TECH, 3: ESTUDIANTE */
	CHARGE ENUM(1, 2, 3) NOT NULL,
	ACTIVE ENUM('ACTIVE', 'VACATION') DEFAULT 'ACTIVE',
	MANAGER_ID INT(8),
	SURROGACY INT(4) DEFAULT 0,
	FOREIGN KEY MANAGER_ID REFERENCES EMPLOYEES(ID)
);

---------------------------------------------------------------------------
---------------------------------------------------------------------------
CREATE TRIGGER VACATION AFTER UPDATE ON EMPLOYEES
FOR EACH ROW
BEGIN
	/* SUPLENCIA */
	IF NEW.ACTIVE LIKE 'VACATION' AND OLD.ACTIVE NOT LIKE 'VACATION' THEN
		BEGIN
			/* LOS ESTUDIANTES NO TIENEN SUBORDINADOS */
			IF NEW.CHARGE < 3 THEN
				BEGIN
					/* SELECCIONAR SUPLENTE  */
					DECLARE @SUPL_ID INT(8);
					DECLARE @SUPL_CHARGE INT(1);
					@SUPL_ID, @SUPL_CHARGE = SELECT ID, CHARGE FROM EMPLOYEES
												WHERE MANAGER_ID LIKE NEW.ID
												ORDER BY START_DATE ASC
												LIMIT 1;

					/* AUMENTAR CATEGORÍA DEL SUPLENTE */
					UPDATE EMPLOYEES
					 SET CHARGE = @SUPL_CHARGE - 1, SURROGACY = SURROGACY + 1
					 WHERE ID == @SUPL_ID;
				END;
			END IF;
		END;

	/* DESHACER SUPLENCIA */
	ELSEIF NEW.ACTIVE LIKE 'ACTIVE' AND OLD.ACTIVE LIKE 'VACATION' THEN
		BEGIN
		/* LOS ESTUDIANTES NO TIENEN SUBORDINADOS */
			IF NEW.CHARGE < 3 THEN
				BEGIN
					/* SELECCIONAR SUPLENTE  */
					DECLARE @SUPL_ID INT(8);
					DECLARE @SUPL_CHARGE INT(1);
					@SUPL_ID, @SUPL_CHARGE = SELECT ID, CHARGE
												FROM EMPLOYEES
												WHERE MANAGER_ID LIKE NEW.ID
												ORDER BY START_DATE ASC
												LIMIT 1;

					/* DISMINUIR CATEGORÍA DEL SUPLENTE */
					UPDATE EMPLOYEES
					 SET CHARGE = @SUPL_CHARGE + 1
					 WHERE ID == @SUPL_ID;
				END;
			END IF;
		END;
	END IF;
END;

------------------------------------------------------------------------------
------------------------------------------------------------------------------
CREATE TRIGGER ON_LEAVING AFTER DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
	/* LOS ESTUDIANTES NO TIENEN SUBORDINADOS */
	IF NEW.CHARGE < 3 THEN
		BEGIN
			/* SELECCIONAR ASCENSO */
			DECLARE @SUPL_ID INT(8);
			DECLARE @SUPL_CHARGE INT(1);

			@SUPL_ID, @SUPL_CHARGE = SELECT ID, CHARGE
										FROM EMPLOYEES
										WHERE MANAGER_ID LIKE OLD.ID
										ORDER BY SURROGACY DESC, START_DATE ASC
										LIMIT 1;

			/* ASCENDER EMPLEADO */
			UPDATE EMPLOYEES
				SET CHARGE = @SUPL_CHARGE - 1, SURROGACY = 0
				WHERE ID == @SUPL_ID;
		END;
	END IF;
END;